index:
    path: /
    controller: App\Controller\DefaultController::index

registration:
    path: /registration
    controller: App\Controller\UserController::registrationUser

app_login:
    path: /login
    controller: App\Controller\UserController::login
